const data =   [
    { 
      "id" : "1",
      "uuid": "AB-221",
      "image": "https://res.cloudinary.com/dhu2tfdji/image/upload/v1629503125/maskapai/garuda-indonesia-logo-BD82882F07-seeklogo_1_wnym1s.png",
      "maskapai" : "Garuda Indonesia",
      "from": "IND",
      "to": "JPG",
      "time": {
            "depature": "00:00",
            "arrived": "04:00",
            "transit": "1",
          },
       "price": {
            "idclass": 3,
            "class": "Economy",
            "adult": 120,
            "child": 80,
          },
       "date": "Monday, 20 july 20",
       "chairsAmount": 108,
       "gate": 221,
       "terminal": "A",
    },
    { 
        "id" : "1",
        "uuid": "AB-221",
        "image": "https://res.cloudinary.com/dhu2tfdji/image/upload/v1629503132/maskapai/Lion_Air_logo_logotype_1_f5vwrl.png",
        "maskapai" : "Garuda Indonesia",
        "from": "IND",
        "to": "JPG",
        "time": {
              "depature": "00:00",
              "arrived": "04:00",
              "transit": "2",
            },
         "price": {
              "idclass": 3,
              "class": "Economy",
              "adult": 120,
              "child": 80,
            },
         "date": "Monday, 20 july 20",
         "chairsAmount": 108,
         "gate": 221,
         "terminal": "A",
      },
      { 
        "id" : "1",
        "uuid": "AB-221",
        "image": "https://res.cloudinary.com/dhu2tfdji/image/upload/v1629503118/maskapai/AIR_ASIA_1_1_vywjla.png",
        "maskapai" : "Garuda Indonesia",
        "from": "IND",
        "to": "JPG",
        "time": {
              "depature": "00:00",
              "arrived": "04:00",
              "transit": "Direct",
            },
         "price": {
              "idclass": 3,
              "class": "Economy",
              "adult": 120,
              "child": 80,
            },
         "date": "Monday, 20 july 20",
         "chairsAmount": 108,
         "gate": 221,
         "terminal": "A",
      },
      { 
        "id" : "1",
        "uuid": "AB-221",
        "image": "https://res.cloudinary.com/dhu2tfdji/image/upload/v1629503125/maskapai/garuda-indonesia-logo-BD82882F07-seeklogo_1_wnym1s.png",
        "maskapai" : "Garuda Indonesia",
        "from": "IND",
        "to": "JPG",
        "time": {
              "depature": "00:00",
              "arrived": "04:00",
              "transit": "1",
            },
         "price": {
              "idclass": 3,
              "class": "Economy",
              "adult": 120,
              "child": 80,
            },
         "date": "Monday, 20 july 20",
         "chairsAmount": 108,
         "gate": 221,
         "terminal": "A",
      },
      { 
        "id" : "1",
        "uuid": "AB-221",
        "image": "https://res.cloudinary.com/dhu2tfdji/image/upload/v1629503132/maskapai/Lion_Air_logo_logotype_1_f5vwrl.png",
        "maskapai" : "Garuda Indonesia",
        "from": "IND",
        "to": "JPG",
        "time": {
              "depature": "00:00",
              "arrived": "04:00",
              "transit": "1",
            },
         "price": {
              "idclass": 3,
              "class": "Economy",
              "adult": 120,
              "child": 80,
            },
         "date": "Monday, 20 july 20",
         "chairsAmount": 108,
         "gate": 221,
         "terminal": "A",
      }
  ]

  export default data